### ISSUE TITLE
algorithm consult

### ISSUE THREAD

**Issue by TBetterman** [bakshikaivalya/iterative_learning_control#1]
Hello, I am learning iterative learning, I am very interested in your work, can you provide some papers about this project？ I have some troubles about the details of the code. 
Thank you very much

**Comment by bakshikaivalya** [comment]
Hi TBetterman. Sorry for the delay in responding, somehow I missed your message. Here's the best place to get an overview: https://ieeexplore.ieee.org/document/1636313. ILC is essentially the earlier and more rudimentary version of RL and is very useful in a model based framework. Please go ahead and ask me ,more specific questions about the code I have committed.
